import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import ConvexClientProvider from '@/context/ConvexClientProvider';
import { Toaster } from '@/components/ui/sonner';
import { Dialog } from '@/components/ui/dialog';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Scribblet',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <head>
                <link href='/favicon.svg' rel='icon' type='image/svg' />
                <link rel='apple-touch-icon' href='/favicon.svg' type='image/svg' />
            </head>
            <body className={inter.className}>
                <Dialog>
                    <ConvexClientProvider>{children}</ConvexClientProvider>
                </Dialog>
                <Toaster />
            </body>
        </html>
    );
}
